### ISSUE TITLE
Can‘t connect to Disney+

### ISSUE THREAD

**Issue by iDjay** [AdguardTeam/AdGuardVPNForiOS#26]
I can't load the Disney+ app on my iPhone 12 Pro iOS 14.2 with AdGuard VPN 1.0.1 (144).
My account is registered in Germany and I'm connected to a German VPN.
![image](https://user-images.githubusercontent.com/4127356/99067731-7bb49680-25ab-11eb-93bb-c6229eb5364e.png)

**Comment by ameshkov** [comment]
Could you please translate the error message?

**Comment by iDjay** [comment]
@ameshkov just a generic "can't connect to Disney+" message. Works fine when VPN disabled and I don't experience a similar issue with other streaming services.

**Comment by iDjay** [comment]
Could be related to this

https://github.com/AdguardTeam/AdGuardVPNForiOS/issues/11#issuecomment-724653747

**Comment by iDjay** [comment]
Fixed in 1.0.2. thanks!

**Comment by iDjay** [comment]
Issue is back with build 161.

**Comment by ameshkov** [comment]
I am not sure this depends on the app version. This may depend on the server you're using. We also do some changes and migrate some of the locations to different hosting providers, this may also be connected.

**Comment by iDjay** [comment]
I can definitely see this on more apps right now.
Note: DNS is still not in Germany.

**Comment by ameshkov** [comment]
Oh, bot. Just so that it was clear: the issue is not yet resolved, but we're going to implement "streaming-enabled" servers.

**Comment by iDjay** [comment]
@ameshkov some non streaming apps are also not working. I'm pretty sure it's still related to the DNS servers not being in Germany.

**Comment by ameshkov** [comment]
@iDjay hmm, we'll add an option to configure a custom DNS server, this will help testing and confirmng your idea.
